// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package mailbox

import (
	"database/sql"
)

type Mailbox struct {
	ID       int64
	Name     string
	Email    string
	Message  string
	Date     int64
	Approval sql.NullInt64
	Isread   sql.NullInt64
}
