http:
  routers:
    checklist:
      entrypoints: web
      rule: Host(`elisa-adam.com`)
      service: website
  services:
    website:
      loadBalancer:
        servers:
          - url: "http://website:80"


