networks:
  traefik-net:
    name: traefik-net
    driver: bridge

services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
    volumes:
      # static conf
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      # dir for dynamic conf
      - "./conf:/etc/traefik/conf:ro"
    networks:
      - traefik-net
  website:
    image: "ghcr.io/hmaier-dev/website-else/public-html"
    container_name: "website"
    networks:
      - traefik-net

