---
name: earthly +build and deployment to vm

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - content/**
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    - name: Download latest earthly
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.8.13/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
    - name: Earthly +build
      run: |
        earthly +build
    - name: Debug
      run: ls -la
    - name: upload ./public as artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: public-html
        path: public/
    - name: upload ./ci as artificat for later testing
      uses: actions/upload-artifact@v4
      with:
        name: ci-dir
        path: ci/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: import ./public artifact
      uses: actions/download-artifact@v4
      with:
        name: public-html
        path: public/
    - name: deploy public directory to vm
      uses: imajeetyadav/rsync-deployer@2.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source_path: ./public
        target_path: ~/
        delete_option: true
        print_summary: true
        print_statistics: true
        debug: false
    - name: run the update-script for html
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: /home/deploy/update-static-html.sh
  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: download ./ci as artificat for testing
      uses: actions/download-artifact@v4
      with:
        name: ci-dir
        path: ci/
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ci/requirements.txt
    - name:
      run: | 
        python ci/check_statuscodes.py
