---
name: Publish to vm

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Earthly +build"]
    types: ["completed"]
    branches:
      - 'main'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run some action
        run: echo "Hello, World!"

